version: '3.8'

services:
  wedding-app:
    image: estelle-matthieu-wedding:latest
    container_name: estelle-matthieu-wedding
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - wedding-network
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wedding.rule=Host(`your-domain.com`)"
      - "traefik.http.services.wedding.loadbalancer.server.port=80"
      - "com.docker.compose.project=estelle-matthieu-wedding"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  wedding-network:
    driver: bridge
